output_dir: "D:/Dev/repos/deepcheap/DeepFace_Orig/pretrain"
pretrained_modelpath: "D:/Dev/repos/deepcheap/DeepFace_Orig/pretrain/model.tar"
dataset:
  batch_size: 1
  training_data: ['celeba']
  K: 1
train:
  train_detail: True
  resume: True
  max_epochs: 10
  max_steps: 1000000
  log_steps: 10
  vis_steps: 500
  checkpoint_steps: 1000
  val_steps: 500
  eval_steps: 1000

# python main_train_deca_release.py --cfg configs/release_version/deca_detail.yml