output_dir: "C:/Users/xpand/Desktop/Workspace/DeepFace_Orig/pretrain"
pretrained_modelpath: "C:/Users/xpand/Desktop/Workspace/DeepFace_Orig/pretrain/model.tar"
dataset:
  batch_size: 2
  K: 1
train:
  train_detail: True
  resume: True
  max_epochs: 10
  max_steps: 1000000
  log_steps: 10
  vis_steps: 500
  checkpoint_steps: 1
  val_steps: 500
  eval_steps: 1000
dataset:
  training_data: ['celeba']
# python main_train_deca_release.py --cfg configs/release_version/deca_detail.yml